### ISSUE TITLE
low platform adoption due to nonstandard login process

### ISSUE THREAD

**Issue by saadcaffeine** [interfacerproject/interfacer-gui#788]
New user onboarding process needs a bit of work. Using a non-standard method of sign-in to the platform introduces an unexpected hurdle for me, this prevents me from recommending the use of this platform to others. The passphrase may be a brilliant way to keep everything more secure but users are required to write this down and carry it around with them if they're to use the platform. I suggest adding a more familiar way to sign-in that would greatly improve platform adoption.

**Comment by andrea-dintino** [comment]
@saadcaffeine thanks for your feedback. The passphrase is necessary in Interfacer to generate a secret key which is used for signing DPP objects. By remobving the passphrase, half of the application needs to be rewritten, the level of securty would drop considerably. 

Also please note that, if you use the sign-up properly (answering the questions in a way that makes sense), you should probably not need to write down the passphrase: we presume this as the questions are inspired from existing widely deployed applications (e.g. Microsoft Windows) which use the technique in order to uniquely identify users.... did you realize this part?

Said that: how would you recommend improving the sign up process?

**Comment by saadcaffeine** [comment]
Thank you for your response, I appreciate that the DPP requires the secret
key for signing, I would suggest we decouple that from the user sign-up and
sign-in mechanism. I understand this is a design decision and security must
be maintained but I still feel the current user on-boarding process is
getting in the way of more users adopting the platform.

My suggestion for improving the sign-up process is to offer other (OpenID
Connect) mechanisms to sign-in. Most users are already accustomed to this:
[image: image.png]
However in the case of DPP I assume the primary user-base would already
have a github account, so maybe a "Continue with Github" would work better.

**Comment by andrea-dintino** [comment]
Thanks for the recommendation. 
This would require a considerable implementation effort, so this is not something we can consider at this point.
